<a href="https://colab.research.google.com/github/HPAndres/UDA_DeepLearning/blob/main/PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: torch code example

!pip install torch


  Using cached nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Using cached nvidia_cublas_

In [ ]:
import torch
import numpy as np

In [ ]:
# Create a tensor
x = torch.tensor([1.0, 2.0, 3.0])
print(x)

# Perform operations on the tensor
y = x + 2
print(y)

tensor([1., 2., 3.])
tensor([3., 4., 5.])


In [ ]:
data = [[1,2],[3,4],[5,6]]
np_data = np.array(data)
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
torch.rand(3,3,3)

tensor([[[0.0874, 0.9499, 0.6477],
         [0.3816, 0.6128, 0.0350],
         [0.4848, 0.0132, 0.4473]],

        [[0.9613, 0.0982, 0.4032],
         [0.7326, 0.1652, 0.8912],
         [0.3413, 0.4823, 0.9405]],

        [[0.9102, 0.4761, 0.7063],
         [0.9642, 0.0537, 0.3580],
         [0.4757, 0.1382, 0.1160]]])

In [ ]:
rand1 = torch.rand(5,5)
rand2 = torch.rand(5,5)
torch.matmul(rand1, rand2)

tensor([[0.6612, 1.2813, 1.7210, 1.4118, 0.7112],
        [0.3913, 0.9039, 1.1538, 1.3230, 0.6783],
        [0.7833, 1.6281, 1.9238, 1.9419, 1.0720],
        [0.9714, 1.9777, 2.3203, 2.3286, 1.0930],
        [0.4786, 1.0358, 1.1840, 1.0690, 0.6679]])